[project]
name = "voice-agent-project"
version = "0.1.0"
description = "University Admission & Student Info Voice Call Agent"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=1.26.0",
    "psycopg2-binary>=2.9.9",
    "requests>=2.31.0",
    "sarvamai==0.1.31a4",
    "sounddevice>=0.4.6",
    "soundfile>=0.12.1",
    "websockets>=12.0",
]
